# Generated by Django 6.0.3 on 2026-04-02 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0002_seed_nizhny_map_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPointCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Map point category',
                'verbose_name_plural': 'Map point categories',
                'ordering': ('sort_order', 'title', 'id'),
            },
        ),
        migrations.AddField(
            model_name='mappoint',
            name='address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='short_description',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='working_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='points', to='map_points.mappointcategory'),
        ),
        migrations.CreateModel(
            name='MapPointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('position', models.PositiveIntegerField(default=0)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map_points.mappoint')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MapPointReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='map_points.mappoint')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
