# Generated by Django 6.0.3 on 2026-04-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_banned_at_user_warning_count_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
