# Generated by Django 6.0.3 on 2026-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_instagram_url_user_telegram_url_user_vk_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('support', 'Support'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=24),
        ),
    ]
