# Generated by Django 6.0.3 on 2026-04-03 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map_points', '0007_mappointreviewimage'),
        ('posts', '0008_rebrand_app_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('general', 'General'), ('account', 'Account'), ('content', 'Content'), ('map', 'Map'), ('report', 'Report')], default='general', max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_support', 'Waiting support'), ('waiting_user', 'Waiting user'), ('closed', 'Closed')], default='waiting_support', max_length=24)),
                ('last_message_at', models.DateTimeField()),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('unread_for_user_count', models.PositiveIntegerField(default=0)),
                ('unread_for_support_count', models.PositiveIntegerField(default=0)),
                ('is_bot_enabled', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_threads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_message_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('support', 'Support')], max_length=16)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportthread')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('map_review', 'Map review')], max_length=24)),
                ('target_snapshot', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('misinformation', 'Misinformation'), ('dangerous', 'Dangerous content'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='posts.postcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='posts.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='map_points.mappointreview')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL)),
                ('support_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_report', to='support.supportthread')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
