# Generated by Django 6.0.3 on 2026-04-04 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _resolve_event_date(dt):
    if not dt:
        return None
    if timezone.is_aware(dt):
        return timezone.localtime(dt).date()
    return dt.date()


def populate_event_dates(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.filter(kind="event", event_date__isnull=True).iterator():
        post.event_date = _resolve_event_date(post.event_starts_at) or _resolve_event_date(post.published_at)
        if post.event_date is not None:
            post.save(update_fields=["event_date"])


def clear_event_dates(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    Post.objects.filter(kind="event").update(event_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rebrand_app_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_event_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_event_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_event_dates, clear_event_dates),
    ]
