# Generated by Django 6.0.3 on 2026-04-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='support.contentreport'),
        ),
        migrations.AddField(
            model_name='notification',
            name='support_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='support.supportthread'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_liked', 'Post liked'), ('post_commented', 'Post commented'), ('support_thread_created', 'Support thread created'), ('support_message_received', 'Support message received'), ('report_created', 'Report created'), ('report_updated', 'Report updated')], max_length=32),
        ),
    ]
